apiVersion: v1
kind: Pod
metadata:
  name: tmp-pod
spec:
  tolerations:
  - key: service
    value: buffer
    operator: Equal
    effect: NoSchedule
  containers:
  - image: busybox
    name: tmp-pod
    command: ["sh", "-c", "--"]
    args: ["while true; do sleep 3600; done"]
