apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:
  containers:
  - image: nginx
    name: nginx-container
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - image: debian
    name: debian-container
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["sh", "-c", "--"]
    args: ["echo HelloWorld > /pod-data/index.html"]
  volumes:
  - name: shared-data
    emptyDir: {}

