server:
  enabled: true

  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    mountPath: /data
    size: 100Gi
  replicaCount: 1

  ## Prometheus data retention period (default if not specified is 15 days)
  ##
  retention: "15d"

  tolerations:
    - key: service
      value: buffer
      operator: Equal
      effect: NoSchedule

alertmanager:
  tolerations:
    - key: service
      value: buffer
      operator: Equal
      effect: NoSchedule
  
pushgateway:
  tolerations:
    - key: service
      value: buffer
      operator: Equal
      effect: NoSchedule

