apiVersion: v1
kind: Service
metadata:
  name: http-go-svc
  labels:
    app: http-go-svc
spec:
  type: ClusterIP
  # sessionAffinity: ClientIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
#    - name: origin # 다중 포트 서비스시 name 옵션 필수
#      port: 8080
#      protocol: TCP
#      targetPort: 8080
  selector:
    app: http-go
