apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tmp
  name: tmp
spec:
  tolerations:
    - key: service
      value: buffer
      operator: Equal
      effect: NoSchedule
  containers:
  - image: busybox
    name: tmp
    command: ["sh", "-c", "--"]
    args: ["sleep infinity"]
