
apiVersion: v1
kind: Service
metadata:
  name: http-go-np
  labels:
    app: http-go-np
spec:
  type: NodePort
  selector:
    app: http-go
  ports:
  - port: 80 # 서비스의 포트
    protocol: TCP
    targetPort: 8080 # 파드의 포트
    nodePort: 30001 # 최종적으로 서비스되는 포트
    

