apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::225953240914:role/service-role/zero-codebuild-role
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::225953240914:role/zero-codebuild-role
      username: build
      groups:
        - system:masters
