
apiVersion: v1
kind: Service
metadata:
  name: http-go-lb
  labels:
    app: http-go-lb
spec:
  type: LoadBalancer
  selector:
    app: http-go
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    # nodePort: 30001
    

