
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3

      
      #http.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
      #    duration := time.Now().Sub(started)
      #    if duration.Seconds() > 10 {
      #        w.WriteHeader(500)
      #        w.Write([]byte(fmt.Sprintf("error: %v", duration.Seconds())))
      #    } else {
      #        w.WriteHeader(200)
      #        w.Write([]byte("ok"))
      #    }
      #})
