
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-go
  name: http-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-go
  strategy: {}
  template:
    metadata:
      labels:
        app: http-go
    spec:
      containers:
      - image: gasbugs/http-go
        name: http-go

---

apiVersion: v1
kind: Service
metadata:
  name: http-go-svc
  labels:
    app: http-go-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: http-go

