apiVersion: v1
kind: Pod
metadata:
  name: command-demo2
spec:
  containers:
  - image: debian
    name: command-demo-container
    command: ["/bin/echo"]
    args: ["$(MESSAGE)"]
    env:
    - name: MESSAGE
      value: "Hello world"
  restartPolicy: OnFailure
