apiVersion: v1
kind: Pod
metadata:
  name: command-demo
spec:
  containers:
  - image: debian
    name: command-demo-container
    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]
  restartPolicy: OnFailure
