apiVersion: v1
kind: Pod
metadata:
  name: while-demo
spec:
  containers:
  - image: busybox
    name: while-demo-container
    command: ["sh", "-c", "--"]
    args: ["while true; do echo Hello && sleep 3600; done;"]
  restartPolicy: OnFailure
