
apiVersion: v1
kind: ServiceAccount
metadata:
  name: busybox-sa

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-sa
spec:
  serviceAccountName: busybox-sa
  containers:
  - image: busybox
    name: pod-sa
    command: ["sh", "-c", "--"]
    args: ["while true; do sleep 3600; done;"]

