apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
spec:
  containers:
  - image: gcr.io/google-samples/node-hello:1.0
    name: envar-demo-container
    env:
    - name: DEMO_GREETING
      valueFrom:
        configMapKeyRef:
          name: map-name
          key: test
