
apiVersion: v1
kind: Pod
metadata:
  name: http-go-v3
  labels:
    creation_method: manual-v3
spec:
  containers:
  - name: http-go
    image: gasbugs/http-go
    ports:
    - containerPort: 8080
      protocol: TCP


# kubectl create -f go-http-pod-v3.yaml
# kubectl get pod --show-labels
# kubectl get pod -L env,creation_method
# kubectl get pod -l env
