apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
spec:
  containers:
  - image: gcr.io/google-samples/node-hello:1.0
    name: envar-demo-container
    env:
    - name: ID
      valueFrom:
        secretKeyRef:
          name: db-user-pass
          key: id
    - name: PW
      valueFrom:
        secretKeyRef:
          name: db-user-pass
          key: pw
