apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - key: "service"
        value: buffer
        operator: Equal
        effect: "NoSchedule"
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: 
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 100Mi
            cpu: 150m
status: {}
