
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx
  #  labels:
  #    app: guestbook
  #    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rs-nginx
  template:
    metadata:
      labels:
        app: rs-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          protocol: TCP

